version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "10:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    groups:
      routine-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      security-dependencies:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: "10:00"
      timezone: Asia/Shanghai
    groups:
      routine-actions:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      security-actions:
        applies-to: security-updates
        patterns:
          - "*"
